export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";

// USERS
export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAIL = "LOAD_USERS_FAIL";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const UPDATE_ACCOUNT_STATUS_START = "UPDATE_ACCOUNT_STATUS_START";
export const UPDATE_ACCOUNT_STATUS_SUCCESS = "UPDATE_ACCOUNT_STATUS_SUCCESS";
export const UPDATE_ACCOUNT_STATUS_FAIL = "UPDATE_ACCOUNT_STATUS_FAIL";

// VISITS
export const LOAD_VISITS_START = "LOAD_VISITS_START";
export const LOAD_VISITS_SUCCESS = "LOAD_VISITS_SUCCESS";
export const LOAD_VISITS_FAIL = "LOAD_VISITS_FAIL";

export const CREATE_VISIT_START = "CREATE_VISIT_START";
export const CREATE_VISIT_SUCCESS = "CREATE_VISIT_SUCCESS";
export const CREATE_VISIT_FAIL = "CREATE_VISIT_FAIL";

export const DELETE_VISIT_START = "DELETE_VISIT_START";
export const DELETE_VISIT_SUCCESS = "DELETE_VISIT_SUCCESS";
export const DELETE_VISIT_FAIL = "DELETE_VISIT_FAIL";

export const UPDATE_ACCOUNT_VISIT_START = "UPDATE_ACCOUNT_VISIT_START";
export const UPDATE_ACCOUNT_VISIT_SUCCESS = "UPDATE_ACCOUNT_VISIT_SUCCESS";
export const UPDATE_VISIT_STATUS_FAIL = "UPDATE_ACCOUNT_VISIT_FAIL";

// MESSAGES
export const SEND_MESSAGE_START = "SEND_MESSAGE_START";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const LOAD_MESSAGES_START = "LOAD_MESSAGES_START";
export const LOAD_MESSAGES_SUCCESS = "LOAD_MESSAGES_SUCCESS";
export const LOAD_MESSAGES_FAIL = "LOAD_MESSAGES_FAIL";
